// 菜谱数据库 - 严格按餐类区分，早餐无炒菜
const RECIPES = [
  // ==================== 早餐 ====================
  { id:1, name:'隔夜燕麦杯', mealType:'breakfast', category:'diet', calories:340, protein:16, carbs:48, fat:10, time:'5分钟（提前一晚）', difficulty:'简单', ingredients:['燕麦','牛奶','酸奶','奇亚籽','香蕉'], steps:['燕麦+奇亚籽+牛奶混合放入冰箱过夜','早晨取出铺上香蕉片','淋少许蜂蜜即可食用'], tags:['早餐','高纤维','免煮'] },
  { id:2, name:'全麦吐司煎蛋', mealType:'breakfast', category:'diet', calories:310, protein:20, carbs:28, fat:12, time:'10分钟', difficulty:'简单', ingredients:['全麦面包','鸡蛋','黄油','盐','黑胡椒'], steps:['全麦面包烤至微脆','不粘锅小火融化黄油','打入鸡蛋煎至蛋白凝固（约3分钟）','放在吐司上撒盐和黑胡椒即可'], tags:['早餐','高蛋白','快手'] },
  { id:3, name:'香蕉蛋白粉松饼', mealType:'breakfast', category:'diet', calories:320, protein:28, carbs:36, fat:7, time:'15分钟', difficulty:'简单', ingredients:['蛋白粉','香蕉','鸡蛋','燕麦片','泡打粉'], steps:['香蕉压成泥','加入鸡蛋+蛋白粉+燕麦+泡打粉搅匀成糊','不粘锅小火倒入面糊','表面冒泡时翻面再煎1分钟出炉'], tags:['早餐','高蛋白','健身'] },
  { id:4, name:'紫薯鸡蛋卷', mealType:'breakfast', category:'diet', calories:260, protein:14, carbs:32, fat:8, time:'15分钟', difficulty:'简单', ingredients:['紫薯','鸡蛋','牛奶','盐'], steps:['紫薯蒸熟（约12分钟）压泥加少许牛奶调匀','鸡蛋打散加盐摊成薄蛋皮','紫薯泥均匀铺在蛋皮上','从一端卷起切段装盘'], tags:['早餐','高颜值','健康'] },
  { id:5, name:'希腊酸奶碗', mealType:'breakfast', category:'diet', calories:280, protein:22, carbs:30, fat:9, time:'3分钟', difficulty:'简单', ingredients:['希腊酸奶','格兰诺拉麦片','蓝莓','草莓','蜂蜜'], steps:['希腊酸奶倒入碗中','铺上麦片','放上蓝莓和草莓','淋少许蜂蜜即可'], tags:['早餐','快手','高蛋白'] },
  { id:6, name:'水煮蛋+蒸红薯+牛奶', mealType:'breakfast', category:'diet', calories:320, protein:18, carbs:42, fat:8, time:'25分钟', difficulty:'简单', ingredients:['鸡蛋','红薯','牛奶'], steps:['鸡蛋冷水下锅水开煮7分钟捞出过凉水','红薯洗净放蒸锅蒸20分钟至筷子能穿透','搭配一杯热牛奶'], tags:['早餐','基础','饱腹'] },
  { id:7, name:'美式嫩炒蛋+吐司', mealType:'breakfast', category:'diet', calories:340, protein:22, carbs:28, fat:14, time:'8分钟', difficulty:'简单', ingredients:['鸡蛋','牛奶','黄油','全麦面包','盐'], steps:['鸡蛋+牛奶+盐充分打散','不粘锅小火融化黄油','倒入蛋液不停搅拌至嫩滑（约2分钟）','搭配烤脆的全麦面包'], tags:['早餐','高蛋白','嫩滑'] },
  { id:8, name:'牛奶燕麦粥', mealType:'breakfast', category:'diet', calories:280, protein:14, carbs:44, fat:6, time:'5分钟', difficulty:'简单', ingredients:['燕麦片','牛奶','蜂蜜','核桃仁'], steps:['燕麦片+牛奶倒入小锅','小火煮3-5分钟至粘稠中间搅拌防粘','盛碗加核桃仁淋蜂蜜'], tags:['早餐','暖胃','快手'] },
  { id:9, name:'牛油果吐司', mealType:'breakfast', category:'diet', calories:350, protein:14, carbs:28, fat:22, time:'5分钟', difficulty:'简单', ingredients:['牛油果','全麦面包','柠檬','盐','辣椒粉'], steps:['牛油果切开去核压成泥','加几滴柠檬汁和少许盐拌匀','涂在烤脆的全麦面包上','可撒少许辣椒粉增味'], tags:['早餐','健康脂肪','网红'] },
  { id:10, name:'水煮蛋+香蕉+牛奶', mealType:'breakfast', category:'diet', calories:280, protein:18, carbs:36, fat:8, time:'10分钟', difficulty:'简单', ingredients:['鸡蛋','香蕉','牛奶','全麦面包'], steps:['鸡蛋冷水煮7分钟剥壳','热一杯牛奶','香蕉切片搭配全麦面包一起吃'], tags:['早餐','基础','快手'] },

  // ==================== 午餐 ====================
  { id:11, name:'香煎鸡胸配糙米饭+西兰花', mealType:'lunch', category:'diet', calories:450, protein:42, carbs:48, fat:10, time:'25分钟', difficulty:'简单', ingredients:['鸡胸肉','糙米饭','西兰花','橄榄油','盐','黑胡椒'], steps:['鸡胸肉用盐和黑胡椒腌制10分钟','平底锅中火喷油每面煎5分钟至金黄','西兰花焯水2分钟捞出','搭配一碗糙米饭摆盘'], tags:['午餐','高蛋白','均衡'] },
  { id:12, name:'番茄鸡胸肉丸汤+米饭', mealType:'lunch', category:'diet', calories:420, protein:38, carbs:48, fat:10, time:'25分钟', difficulty:'简单', ingredients:['鸡胸肉','番茄','鸡蛋','葱','姜','盐'], steps:['鸡胸肉剁成泥加蛋清搅拌上劲','番茄切块炒出汁加水烧开','勺子挖肉泥做成丸子下锅','煮5分钟至丸子浮起加盐撒葱配米饭'], tags:['午餐','高蛋白','暖汤'] },
  { id:13, name:'照烧鸡腿饭', mealType:'lunch', category:'diet', calories:480, protein:36, carbs:52, fat:15, time:'25分钟', difficulty:'中等', ingredients:['鸡腿','米饭','西兰花','生抽','蜂蜜','料酒','姜'], steps:['鸡腿去骨用叉子扎孔','生抽+蜂蜜+料酒+姜片调汁腌制15分钟','皮朝下小火煎至金黄翻面','倒入剩余酱汁收浓切块配米饭西兰花'], tags:['午餐','高蛋白','日式'] },
  { id:14, name:'清蒸鲈鱼+杂粮饭', mealType:'lunch', category:'diet', calories:420, protein:38, carbs:42, fat:12, time:'25分钟', difficulty:'简单', ingredients:['鲈鱼','姜','葱','蒸鱼豉油','杂粮饭'], steps:['鲈鱼处理干净两面划刀铺姜片葱段','蒸锅水开大火蒸8-10分钟','倒掉蒸出的汤汁淋蒸鱼豉油','热油浇在葱丝上激出香味配杂粮饭'], tags:['午餐','高蛋白','清蒸'] },
  { id:15, name:'牛肉炒西兰花+米饭', mealType:'lunch', category:'diet', calories:430, protein:38, carbs:42, fat:14, time:'20分钟', difficulty:'简单', ingredients:['牛肉','西兰花','蒜','生抽','蚝油','米饭'], steps:['牛肉切薄片用生抽+淀粉腌制','西兰花焯水2分钟','大火热锅少油牛肉快炒至变色盛出','同锅炒西兰花倒回牛肉加蚝油翻匀配米饭'], tags:['午餐','高蛋白','快手'] },
  { id:16, name:'虾仁滑蛋饭', mealType:'lunch', category:'diet', calories:420, protein:34, carbs:48, fat:10, time:'15分钟', difficulty:'简单', ingredients:['虾仁','鸡蛋','米饭','葱','料酒','盐'], steps:['虾仁用料酒盐腌制5分钟','鸡蛋+少许水打散','虾仁先炒至变色盛出','小火炒蛋至半凝固倒回虾仁轻轻推炒盖在饭上'], tags:['午餐','高蛋白','嫩滑'] },
  { id:17, name:'番茄鸡蛋面', mealType:'lunch', category:'diet', calories:400, protein:18, carbs:56, fat:12, time:'15分钟', difficulty:'简单', ingredients:['面条','鸡蛋','番茄','葱','盐','生抽'], steps:['番茄切块炒出汁加水烧开','打入鸡蛋搅散','放入面条煮熟','加盐生抽调味撒葱花'], tags:['午餐','家常','暖胃'] },
  { id:18, name:'孜然鸡胸肉丁+米饭', mealType:'lunch', category:'diet', calories:420, protein:38, carbs:46, fat:10, time:'15分钟', difficulty:'简单', ingredients:['鸡胸肉','洋葱','青椒','孜然粉','辣椒粉','米饭'], steps:['鸡胸肉切丁用料酒腌制','洋葱青椒切块','大火炒鸡丁至变色','加洋葱青椒翻炒撒孜然辣椒粉配米饭'], tags:['午餐','高蛋白','烧烤味'] },
  { id:19, name:'鸡胸时蔬炒饭', mealType:'lunch', category:'diet', calories:440, protein:36, carbs:50, fat:10, time:'15分钟', difficulty:'简单', ingredients:['鸡胸肉','糙米饭','胡萝卜','青豆','玉米','鸡蛋'], steps:['鸡胸肉切丁胡萝卜切丁','鸡蛋先炒散盛出','炒鸡丁至变色加蔬菜丁','加糙米饭和鸡蛋生抽炒匀'], tags:['午餐','高蛋白','一锅出'] },
  { id:20, name:'香菜拌牛肉+米饭', mealType:'lunch', category:'diet', calories:430, protein:38, carbs:44, fat:14, time:'15分钟', difficulty:'简单', ingredients:['牛肉','香菜','蒜','生抽','醋','花椒油','米饭'], steps:['牛肉切薄片沸水快速焯30秒立即捞出','香菜切段蒜切末','生抽+醋+蒜+花椒油调成酱汁','牛肉+香菜+酱汁拌匀配米饭'], tags:['午餐','高蛋白','爽口'] },

  // ==================== 晚餐 ====================
  { id:21, name:'番茄菌菇豆腐汤', mealType:'dinner', category:'diet', calories:180, protein:14, carbs:16, fat:6, time:'15分钟', difficulty:'简单', ingredients:['嫩豆腐','番茄','金针菇','鸡蛋','葱','盐'], steps:['番茄切块炒出汁加水烧开','加入金针菇和豆腐块煮5分钟','淋入蛋液搅出蛋花','加盐撒葱花出锅'], tags:['晚餐','低卡','暖汤'] },
  { id:22, name:'清蒸鳕鱼+时蔬', mealType:'dinner', category:'diet', calories:280, protein:32, carbs:12, fat:10, time:'20分钟', difficulty:'简单', ingredients:['鳕鱼','姜','葱','蒸鱼豉油','西兰花'], steps:['鳕鱼放姜片葱段上蒸锅大火蒸8分钟','西兰花焯水2分钟','倒掉蒸鱼的汤汁淋蒸鱼豉油','热油浇在葱丝上激香'], tags:['晚餐','高蛋白','清蒸'] },
  { id:23, name:'冬瓜排骨汤', mealType:'dinner', category:'diet', calories:300, protein:24, carbs:16, fat:14, time:'50分钟', difficulty:'简单', ingredients:['排骨','冬瓜','姜','枸杞','盐'], steps:['排骨冷水下锅焯水去血沫捞出','冬瓜去皮切大块','排骨+姜片+足量水大火烧开转小火炖30分钟','加冬瓜再炖15分钟加盐枸杞即可'], tags:['晚餐','暖汤','低卡'] },
  { id:24, name:'蒜蓉蒸茄子', mealType:'dinner', category:'diet', calories:120, protein:4, carbs:16, fat:4, time:'15分钟', difficulty:'简单', ingredients:['茄子','蒜','生抽','醋','香油','葱'], steps:['茄子对半切开上蒸锅蒸10分钟至软','蒜剁成蓉加生抽+醋+香油调汁','茄子撕成条码盘','淋上调好的酱汁撒葱花'], tags:['晚餐','低卡','素菜'] },
  { id:25, name:'凉拌鸡丝', mealType:'dinner', category:'diet', calories:220, protein:32, carbs:8, fat:7, time:'15分钟', difficulty:'简单', ingredients:['鸡胸肉','黄瓜','香菜','蒜','生抽','醋','花椒油'], steps:['鸡胸肉冷水下锅煮8分钟关火焖5分钟','捞出放凉撕成丝','黄瓜切丝蒜切末','鸡丝+黄瓜+蒜+生抽+醋+花椒油拌匀撒香菜'], tags:['晚餐','高蛋白','凉菜'] },
  { id:26, name:'蔬菜沙拉+鸡胸肉', mealType:'dinner', category:'diet', calories:280, protein:32, carbs:14, fat:12, time:'10分钟', difficulty:'简单', ingredients:['鸡胸肉','生菜','番茄','黄瓜','玉米粒','橄榄油','醋'], steps:['鸡胸肉煮熟切片','生菜撕碎番茄黄瓜切片','所有食材混合','橄榄油+醋+盐调成油醋汁淋上'], tags:['晚餐','沙拉','轻食'] },
  { id:27, name:'泡菜豆腐锅', mealType:'dinner', category:'diet', calories:240, protein:18, carbs:16, fat:12, time:'15分钟', difficulty:'简单', ingredients:['嫩豆腐','泡菜','金针菇','鸡蛋','葱'], steps:['泡菜切段锅中少油炒香','加水烧开放入豆腐块','加金针菇煮5分钟','打入鸡蛋煮1分钟撒葱花'], tags:['晚餐','韩式','低卡'] },
  { id:28, name:'紫菜蛋花汤+蒸虾', mealType:'dinner', category:'diet', calories:240, protein:28, carbs:10, fat:8, time:'15分钟', difficulty:'简单', ingredients:['鸡蛋','紫菜','虾','姜','葱','盐','香油'], steps:['虾去虾线加姜片蒸8分钟','另锅水烧开放入紫菜','淋入蛋液搅出蛋花','加盐香油葱花搭配蒸虾吃'], tags:['晚餐','高蛋白','快手'] },
  { id:29, name:'蚝油生菜+水煮蛋', mealType:'dinner', category:'diet', calories:180, protein:12, carbs:14, fat:6, time:'10分钟', difficulty:'简单', ingredients:['生菜','鸡蛋','蚝油','蒜','生抽'], steps:['鸡蛋冷水煮7分钟剥壳','生菜焯水30秒捞出摆盘','蒜末爆香加蚝油+生抽+水勾薄芡','芡汁淋在生菜上搭配水煮蛋'], tags:['晚餐','低卡','素菜'] },
  { id:30, name:'味噌汤+饭团', mealType:'dinner', category:'diet', calories:260, protein:12, carbs:42, fat:5, time:'15分钟', difficulty:'简单', ingredients:['味噌','嫩豆腐','海带','米饭','海苔'], steps:['水烧开加海带豆腐煮3分钟','关火后融入味噌（不要沸腾）','米饭捏成三角饭团包上海苔','汤和饭团搭配食用'], tags:['晚餐','日式','清淡'] },

  // ==================== 放纵餐 ====================
  { id:31, name:'经典牛肉汉堡', mealType:'lunch', category:'cheat', calories:650, protein:35, carbs:48, fat:36, time:'20分钟', difficulty:'中等', ingredients:['牛肉','汉堡胚','芝士','生菜','番茄','洋葱'], steps:['牛肉剁成肉饼加盐胡椒','大火煎每面3分钟放芝士片盖上','汉堡胚烤热','组装:底胚+生菜+肉饼+番茄+洋葱+上胚'], tags:['放纵餐','汉堡','自制'] },
  { id:32, name:'奶油培根意面', mealType:'lunch', category:'cheat', calories:620, protein:24, carbs:52, fat:36, time:'20分钟', difficulty:'中等', ingredients:['意面','培根','淡奶油','芝士','蛋黄','蒜'], steps:['意面煮熟沥干培根煎酥','蛋黄+淡奶油+芝士碎混合','意面趁热快速拌入蛋奶液和培根','撒大量黑胡椒即可'], tags:['放纵餐','浓郁','西式'] },
  { id:33, name:'红烧肉+米饭', mealType:'lunch', category:'cheat', calories:680, protein:20, carbs:55, fat:42, time:'1小时', difficulty:'中等', ingredients:['五花肉','冰糖','生抽','老抽','八角','姜','料酒','米饭'], steps:['五花肉切块焯水','冰糖小火炒至琥珀色糖色','加肉翻炒上色','加调料+水小火炖40分钟收汁配米饭'], tags:['放纵餐','经典','下饭神器'] },
  { id:34, name:'麻辣香锅', mealType:'lunch', category:'cheat', calories:650, protein:35, carbs:38, fat:36, time:'25分钟', difficulty:'中等', ingredients:['虾','牛肉','藕片','土豆','花菜','火锅底料','干辣椒'], steps:['所有食材分别焯熟或炸熟','锅中少油炒香火锅底料+干辣椒+花椒','所有食材倒入大火翻炒均匀','出锅撒白芝麻'], tags:['放纵餐','麻辣','聚会'] },
  { id:35, name:'意大利肉酱面', mealType:'lunch', category:'cheat', calories:580, protein:28, carbs:56, fat:26, time:'30分钟', difficulty:'中等', ingredients:['意面','牛肉末','番茄','洋葱','蒜','番茄酱','芝士'], steps:['洋葱蒜炒香加牛肉末炒散','加番茄块和番茄酱小火炖15分钟','意面煮熟沥干拌入肉酱','撒帕玛森芝士碎'], tags:['放纵餐','经典','意面'] },
  { id:36, name:'可乐鸡翅', mealType:'lunch', category:'cheat', calories:500, protein:28, carbs:35, fat:24, time:'30分钟', difficulty:'简单', ingredients:['鸡翅','可乐','生抽','老抽','姜','料酒'], steps:['鸡翅两面划刀焯水','锅中少油煎至两面金黄','倒入可乐+生抽+老抽+姜片','大火烧开转小火收汁至浓稠挂满鸡翅'], tags:['放纵餐','经典','下饭'] },
  { id:37, name:'芝士焗饭', mealType:'lunch', category:'cheat', calories:580, protein:22, carbs:56, fat:30, time:'25分钟', difficulty:'简单', ingredients:['米饭','芝士','培根','玉米粒','青豆','番茄酱'], steps:['米饭铺在烤盘底部','铺上培根玉米青豆','挤番茄酱撒大量芝士','烤箱200°C烤10-12分钟至芝士融化金黄'], tags:['放纵餐','芝士','焗饭'] },
  { id:38, name:'糖醋里脊', mealType:'lunch', category:'cheat', calories:550, protein:28, carbs:45, fat:28, time:'25分钟', difficulty:'中等', ingredients:['猪里脊','鸡蛋','面粉','番茄酱','糖','醋'], steps:['里脊切条用盐料酒腌制','鸡蛋+面粉调糊里脊裹糊','油温六成热炸至金黄捞出','番茄酱+糖+醋调汁翻炒里脊裹匀'], tags:['放纵餐','酸甜','经典'] },
  { id:39, name:'自制披萨', mealType:'lunch', category:'cheat', calories:700, protein:28, carbs:65, fat:35, time:'1小时', difficulty:'中等', ingredients:['面粉','酵母','芝士','番茄酱','培根','青椒'], steps:['面粉+酵母+水揉面发酵30分钟','擀成饼皮涂番茄酱','铺培根青椒撒大量芝士','烤箱220°C烤12-15分钟至芝士冒泡'], tags:['放纵餐','披萨','自制'] },
  { id:40, name:'葱油拌面', mealType:'lunch', category:'cheat', calories:480, protein:14, carbs:56, fat:22, time:'15分钟', difficulty:'简单', ingredients:['面条','葱','生抽','老抽','糖','油'], steps:['葱切段小火慢炸至焦黄（约10分钟）','面条煮熟沥干','炸好的葱油+生抽+老抽+糖拌匀','浇在面上放炸葱段即可'], tags:['放纵餐','面条','经典'] },

  // ==================== 加餐 ====================
  { id:41, name:'蛋白粉奶昔', mealType:'snack', category:'diet', calories:180, protein:30, carbs:8, fat:3, time:'2分钟', difficulty:'简单', ingredients:['蛋白粉','牛奶','香蕉'], steps:['所有材料放入搅拌机','打30秒至顺滑','倒入杯中即可'], tags:['加餐','高蛋白','健身'] },
  { id:42, name:'无糖酸奶+坚果', mealType:'snack', category:'diet', calories:180, protein:12, carbs:12, fat:10, time:'1分钟', difficulty:'简单', ingredients:['无糖酸奶','核桃','杏仁','蓝莓'], steps:['酸奶倒入碗中','撒上核桃杏仁和蓝莓','即可食用'], tags:['加餐','健康脂肪','快手'] },
  { id:43, name:'黄瓜条+鹰嘴豆泥', mealType:'snack', category:'diet', calories:150, protein:8, carbs:18, fat:6, time:'5分钟', difficulty:'简单', ingredients:['黄瓜','鹰嘴豆罐头','柠檬','蒜','盐'], steps:['黄瓜切条','鹰嘴豆+柠檬汁+蒜+盐打成泥','黄瓜条蘸鹰嘴豆泥吃'], tags:['加餐','低卡','高纤维'] }
];
